import {
  faHome,
  faUser,
  faUsers,
  faCog,
  faProjectDiagram,
  faChartSimple,
  faBuildingColumns,
  faMagnifyingGlass,
  faPlus,
  faUserPlus,
  faUserEdit,
  faUserTimes,
  faTrash,
  faEdit,
  faEye,
  faList,
  faDownload,
  faFileAlt,
  faBuilding,
  faSearch,
  faSave,
  faClose,
} from '@fortawesome/free-solid-svg-icons';

export const ICONS = {
  home: faHome,
  user: faUser,
  users: faUsers,
  settings: faCog,
  proyect: faProjectDiagram,
  chart: faChartSimple,
  unidades: faBuildingColumns,
  search: faMagnifyingGlass,
  add: faPlus,
  'user-plus': faUserPlus,
  'user-edit': faUserEdit,
  'user-x': faUserTimes,
  delete: faTrash,
  edit: faEdit,
  eye: faEye,
  list: faList,
  download: faDownload,
  'file-text': faFileAlt,
  building: faBuilding,
  save: faSave,
  close: faClose,
} as const;
